### ISSUE TITLE
Surface refinement node-vertex consistency error on Icelake-client

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#119]
Continued from the end of #118.

```
test$  rm *vtu;pycl test_refinement.py 'test_refine_surfaces(_acf,  "icosphere", True)' 
Traceback (most recent call last):
  File "/home/andreas/src/meshmode/test/test_refinement.py", line 360, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "/home/andreas/src/meshmode/test/test_refinement.py", line 349, in test_refine_surfaces
    refined_mesh = refine_uniformly(mesh, 1)
  File "/home/andreas/src/meshmode/meshmode/mesh/refinement/__init__.py", line 991, in refine_uniformly
    refiner.refine_uniformly()
  File "/home/andreas/src/meshmode/meshmode/mesh/refinement/no_adjacency.py", line 61, in refine_uniformly
    return self.refine(flags)
  File "/home/andreas/src/meshmode/meshmode/mesh/refinement/no_adjacency.py", line 227, in refine
    new_mesh = Mesh(new_vertices, new_el_groups, is_conforming=(
  File "/home/andreas/src/meshmode/meshmode/mesh/__init__.py", line 779, in __init__
    assert _test_node_vertex_consistency(
  File "/home/andreas/src/meshmode/meshmode/mesh/__init__.py", line 983, in _test_node_vertex_consistency
    assert _test_node_vertex_consistency_resampling(mesh, mgrp, tol)
  File "/home/andreas/src/meshmode/meshmode/mesh/__init__.py", line 971, in _test_node_vertex_consistency_resampling
    assert max_el_vertex_error < tol*size, max_el_vertex_error
AssertionError: 9.901371953343942
```

Quite likely a numpy behavior change.

- numpy 1.20 wheel: fine
- numpy 1.20.1 wheel: fine
- `pip install --no-binary ":all:" numpy cython`: (resulting in 1.20.1) error (*only* on my laptop, not on dunkel)

cc @alexfikl because it feels less lonely that way. :)

**Comment by alexfikl** [comment]
Just tried it locally with the newer numpy and can confirm I still can't get it to fail. This is on Comet Lake (and probably many OS differences).

**Comment by inducer** [comment]
Looks like my numpy has bigger problems. It even fails modepy's
```
python test_nodes.py 'test_simp_nodes(3, 6)'  
```
specifically
```
assert (unodes >= -1-eps).all()
```
(And not by a little. One of those node coordinates is -1.03.)

**Comment by inducer** [comment]
I could probably chase this further, but I doubt it's worth it. It'll be some crappy BLAS bug. FWIW, it also fails
```
python -c 'import numpy; numpy.linalg.test()'  
```

**Comment by inducer** [comment]
OK, fine. Feeling charitable: https://github.com/numpy/numpy/issues/18471

And, I'm not falling for this nonsense again: https://gitlab.tiker.net/inducer/akprojects-bin/-/commit/ad245e404813e70a52129544911549918590ca77
